Please be sure your functions work for vectors with a size of three and matrices that are 3x3. Bonus points if you can further generalize them for larger vectors and matrices.

1.	Explain the dot product and cross product in your own words in markdown. Use LaTeX to properly show the equations.

# Dot Product

The dot product tells me how much the vectors move together in the same direction. 
It is the product of the part or length of the vectors that are moving together in the same direction.


How is dot product calculated? 

Dot product is the magnitude(length) of vector A times the magnitude(length) of vector B times the cosine of the angle between the 2 vectors. After doing some manipulation it's clear that the equation is the same as the length of vector B times the part of vector A that goes in the same direction as vector B (or vector B times the adjacent side).  

With 2 dimensional vectors, the dot product is the same as matrix multiplication: mutiplying each value of a vector with the corresponding value in another vector and adding up the products. 

The result or dot product is known as a scaler value (a number, not a vector).

$$ \vec{A} \cdot \vec{B} = \lVert \vec{A} \lVert  \lVert \vec{B} \lVert  \cos(\theta) $$

# Cross Product

The cross product tells me how perpendicular the vectors are. It is the product of the part of a vector that goes in the perpendicular direction to the other vector.

How is cross product calculated?

Cross product is the magnitude(length) of vector A times the magnitude(length) of vector B times the sine of the angle between the 2 vectors. After doing some manipulation it's clear that the equation is the same as the length of vector B times the part of vector A that's going perpendicular to B. 
(or Vector B times the opposite side)

In each part of the cross product calculation, you are leaving out a pair of values from the 2 vectors or the 2 corresponding values from the vectors.

When you calculate the cross product, you get a new vector that is perpendicular to both the vectors. The cross product can only be taken in R3 (3-dimensional).

$$ \vec{A} \cdot \vec{B} = \lVert \vec{A} \lVert  \lVert \vec{B} \lVert  \sin(\theta) $$

# Relationship Between Dot Product and Cross Product

Dot product and cross product are sort of opposite ideas. The dot product is multiplying the part of a vector that goes in the same direction as the other vector. And the cross product is multiplying the part of a vector that goes in the perpendicular direction to the other vector.

MAXIMIZED CROSS PRODUCT: When the two vectors are perpendicular. It'll just be the length of A times the length of B because the sin of 90 degrees is 1.

MINIMIZED DOT PRODUCT: When the two vectors are perpendicular, then there would be no part of vector A that goes in the same direction as vector B. So the dot product is 0 (cos(90) x length of A x length of B).



MINIMIZED CROSS PRODUCT: When the two vectors have no angle, are essentially the same line going in the same direction, then there would be no part of vector A that is perpendicular to vector B. Cross product is 0 (length of A x length of B x sin(0))

MAXIMIZED DOT PRODUCT: When the two vectors have no angle, are essentially the same line going in the same direction. It'll just be the length of A times length of B because the cos of 0 degrees is 1.

2.	Write a function angle_between(v1, v2) where v1 and v2 are two vectors that are passed in, and the angle between them is calculated. 

In [41]:
import numpy as np
import math 

In [46]:
def angle_between(v1, v2):
    
    v1first = v1[0]
    v1second = v1[1]
    v2first = v2[0]
    v2second = v2[1]
    
    #Dot Product: dp = np.dot(v1,v2)
    dp = np.dot(v1,v2)
    
    #two hypotenuse
    h1 = math.sqrt(v1first **2 + v1second **2)
    h2 = math.sqrt(v2first **2 + v2second **2)
    
    #inverse cosine 
    angle = np.arccos(dp / (h1 * h2))
    print(angle)
    


In [47]:
angle_between([3, 6], [4, 8])

1.4901161193847656e-08


3.	Write a function called row_dot(A, r1, r2) which takes an input matrix called A, one row number identified by r1, and another row number identified by r2 and returns the dot product of the r1 and r2 rows (indexing starts at 0).

In [84]:
#takes in matrix of any size (# of rows) and 2 row numbers. The dot product of the 2 rows specified are then calculated. 


    
# x = []
# y = []
#print(sum([i*j for (i, j) in z

#row_dot([[3,2],[2,4]])


def row_dot (A, r1, r2):
    try: 
            DP = np.dot(A[r1-1], A[r2-1])
            print(DP)
    except Exception as e:
        print(e)

        
#y = the product of the corresponding values in the vectors plus the previous product

In [85]:
A = [[1,2,3],
     [2,4,6],
     [3,6,9],
     [4,8,12]]

row_dot (A, 1, 2)

28


In [58]:
def row_dot(A, r1, r2):
    r1 = A[0]
    r2 = A[1]
    dot = (r1[0] * r1[1]) + (r2[0] * r2[1])
    print(dot)


In [65]:
row_dot([[3,2],[2,4]] , [1,2] , [2,4])

14


In [86]:
row_dot (A, 2, 2)

56


4.	Write a function matrix_division(m1, m2) that takes in two matrices, m1 and m2, and returns the result. What is the trick with matrix division?

The closest equivalent is multiplying by the inverse of another matrix. In other words, while [A] ÷ [B] is undefined, you can solve the problem [A] * [B]-1. Since these two equations would be equivalent for scalar quantities, this "feels" like matrix division, but it's important to use the correct terminology.

In [144]:
def matrix_division(m1, m2):
    
    #Confirm the "divisor matrix" is square. 
    if m1.shape[0] != m1.shape[1] or m2.shape[0] != m2.shape[1]:
        print("no unique solution1")
    
    #the number of columns in the first matrix must equal the number of rows in the second matrix 
    if m1.shape[0] == m2.shape[1]:
        print ("no solution")
    if np.linalg.det(m2) == 0:
        print ("no unique solution")
    else:
        #Switch the positions of the elements on the main 2 x 2 diagonal.
        t = m2.T
        #print(t)
        
        #Multiply the top right and bottom left elements by -1:
        t[0,-1] = t[0,-1] * -1 
        t[-1,0] = t[-1,0] * -1
        #print(t)
        
        #Take the reciprocal of the determinant.
        DR = 1 / np.linalg.det(m2)
        #print(DR)
        
        #Multiply the new matrix by the reciprocal of the determinant.  
        inverse_m2 = DR * t
        #print(inverse_m2)
        
        #multiply the two matrices (solution = m1 * inverse_m2)
        solution = np.dot(m1,inverse_m2)
        print(solution)

In [143]:
A = np.array([[13, 26], 
              [20, 30]])

B = np.array([[1, 2],
               [3, 4]])

matrix_division(A, B)

[[ 19.5 -32.5]
 [ 20.  -30. ]]


In [119]:
A = np.array([[13, 26], 
              [20, 30]])

B = np.array([[1, 2],
               [3, 4]])

matrix_division(A, B)

-0.4999999999999999
[[ 19.5 -32.5]
 [ 20.  -30. ]]


In [121]:
A = np.array([[13, 26], 
              [20, 30]])

B = np.array([[-2, 1],
               [3/2, 1/-2]])

np.dot(A,B)

array([[13.,  0.],
       [ 5.,  5.]])

In [98]:
m.shape[0] == m2.shape[1]


True

In [101]:
m.shape[1] - 1

(3, 2)

5.	Write a function is_orthogonal(v1,v2, tol), where v1 and v2 are column vectors of the same size and tol is a scalar value strictly larger than 0. The output should be 1 if the angle between v1 and v2 is within tol of π/2; that is, |π/2−θ|<tol|π/2−θ|<tol, and 0 otherwise. You may assume that v1 and v2 are column vectors of the same size, and that tol is a positive scalar.

In [ ]:
def is_orthogonal(v1,v2,tol):

1) v1, v2 same size
2)tol is a positive scalar
3)tol = scalar value > 0
4)OUTPUT: 1 if angle <  tol(π/2)   |π/2−θ|<tol|π/2−θ|<tol else 0


In [ ]:
def is_orthogonal(v1,v2,tol):
    try:
        if len(v1)!=len(v2):
            print("vector colums are not the same size")
        elif tol <= 0:
            print("tol need to bea positive scalar")
        

6.	Create a class called vector_calculator. __init__ should take self, vector1, and vector2. It should have two methods inside of it that are from problems 1 and 4 above (angle_between and is_orthogonal). Make sure tol is defaulted but can be overwritten. Make sure you can call angle_between and is_orthogonal through the class and return the correct results as in problems 1 and 4. 

7.	Show a graphical representation of the breast cancer data outlined in this reading https://www.datacamp.com/community/tutorials/principal-component-analysis-in-python Be sure to describe what PCA is and incorporate the principal components in your plot. This is just exploratory, so there are many correct answers!

